### ISSUE TITLE
Support split ephys recordings

### ISSUE THREAD

**Issue by bjhardcastle** [AllenInstitute/np_codeocean#4]
Currently, we only upload the largest ephys `Record Node 10x/experiment/recording` folder (matched across ABC & DEF folders), with the expectation that any other folders are short dummy or aborted recordings.

For experiments which stopped due to insufficient disk space, then restarted, we want to upload both, while still discarding any superfluous folders/

# tasks 
- [x] make a modified version of `np_tools.get_filtered_ephys_paths_relative_to_record_node_parents()` that allows optional recording dir names to be passed in, but defaulting to None.
    e.g `def get_split_recording_paths_relative_to_record_node_parents(session, recording_dirs: Iterable[str] | None = None):` (making sure to check if recording_dirs is a str before use)
- [x] add corresponding input argument to `upload.py:upload_session`
https://github.com/AllenInstitute/np_codeocean/blob/d93bb9d233f52e3d44f67b0ea5e0a6d00b04c33f/src/np_codeocean/upload.py#L59-L61
- [x] test before upload
- [x] upload outstanding sessions
- [ ] add argparser to allow this list of recording dir names to be supplied on command line too

**Comment by bjhardcastle** [comment]
Decided to add the parameter and logic to `np_tools.get_filtered_ephys_paths_relative_to_record_node_parents()`

**Comment by bjhardcastle** [comment]
## Testing

1. `"//allen/programs/mindscope/workgroups/dynamicrouting/PilotEphys/Task 2 pilot/DRpilot_686176_20231206": ('recording1', 'recording2')`
  - recording dir names weren't passed correctly to `np_tools` fn, so only `recording1` is being uploaded. Will need to do a second upload + sort

2. `"//allen/programs/mindscope/workgroups/dynamicrouting/PilotEphys/Task 2 pilot/DRpilot_681532_20231019": ('recording1', 'recording2')` 
  - should be correct: check sorting results (spike times should show a gap of 5-10 minutes)
